[package]
authors = ["Chmouel Boudjnah <chmouel@chmouel.com>"]
name = "raffi"
description = "A simple wofi launcher based on YAML file"
version = "0.0.5"
edition = "2021"
readme = "README.md"
license = "Apache-2.0"
categories = ["command-line-utilities"]
keywords = ["task", "command", "launch"]

[dependencies]
gumdrop = { version = "0.8.1" }
serde = { version = "1.0.181", features = ["derive"] }
serde_yaml = "0.9.22"
walkdir = "2.3.3"
